# Publish DEV docker image on push - use it for testing

name: Publish DEV Docker image

on: [push]

jobs:
  push_to_registry:
    name: Push DEV Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: feltlabs/feltlabs-py:dev
          labels: |
            ai.feltlabs.version=${{ github.ref_name }}
            ai.feltlabs.name=feltlabs.py
            ai.feltlabs.description=Docker image for running FELT Labs training algorithms (development version for testing).
            ai.feltlabs.url=https://feltlabs.ai
            ai.feltlabs.build-date=${{ github.event.workflow_run.created_at }}
